App_name = {
  "safari": "/Applications/Safari.app",
  "itunes": "/Applications/iTunes.app",
  "calendar": "/Applications/Calendar.app",
  "contacts": "/Applications/Contacts.app",
  "messages": "/Applications/Messages.app",
  "mail": "/Applications/Mail.app",
  "facetime": "/Applications/FaceTime.app",
  "photos": "/Applications/Photos.app",
  "notes": "/Applications/Notes.app",
  "reminders": "/Applications/Reminders.app",
  "terminal": "/Applications/Utilities/Terminal.app",
  "preview": "/Applications/Preview.app",
  "appstore": "/Applications/App Store.app",
  "systempreferences": "/Applications/System Preferences.app",
  "music": "/Applications/Music.app",
  "maps": "/Applications/Maps.app",
  "calculator": "/Applications/Calculator.app",
  "messages": "/Applications/Messages.app",
  "stickies": "/Applications/Stickies.app",
  "news": "/Applications/News.app",
  "tv": "/Applications/TV.app",
  "podcasts": "/Applications/Podcasts.app",
  "diskutility": "/Applications/Utilities/Disk Utility.app",
  "activitymonitor": "/Applications/Utilities/Activity Monitor.app",
  "console": "/Applications/Utilities/Console.app",
  "keychainaccess": "/Applications/Utilities/Keychain Access.app",
  "textedit": "/Applications/TextEdit.app",
  "systeminformation": "/Applications/Utilities/System Information.app",
  "diskutil": "/sbin/diskutil",
  "activitymonitor": "/Applications/Utilities/Activity Monitor.app",
  "systemuiserver": "/System/Library/CoreServices/SystemUIServer.app",
  "networkutility": "/Applications/Utilities/Network Utility.app",
  "nettop": "/Applications/Utilities/NetTop.app",
  "archey": "/Applications/Utilities/Archey.app",
  "audiomidi": "/Applications/Utilities/Audio MIDI Setup.app",
  "airportutility": "/Applications/Utilities/Airport Utility.app",
  "diskwarrior": "/Applications/Utilities/DiskWarrior.app",
  "adobebridge2020": "/Applications/Adobe Bridge CC 2020.app",
  "launchpad": "/System/Library/CoreServices/Launchpad.app",
  "androidfile": "/Applications/Android File Transfer.app",
  "androidstudio": "/Applications/Android Studio.app",
  "blender": "/Applications/Blender.app",
  "bravebrowser": "/Applications/Brave Browser.app",
  "chromeremote": "/Applications/Google Chrome Remote Desktop Host Uninstaller.app",
  "copyclip": "/Applications/CopyClip.app",
  "dosbox": "/Applications/DOSBox.app",
  "figma": "/Applications/Figma.app",
  "firefox": "/Applications/Firefox.app",
  "googlechrome": "/Applications/Google\ Chrome.app",
  "haptickey": "/Applications/HapticKey.app",
  "jetbrainstoolbox": "/Applications/JetBrains\ Toolbox.app",
  "macsfan": "/Applications/Macs Fan Control.app",
  "memorycleaner": "/Applications/Memory Cleaner 5.app",
  "memorydiag": "/Applications/Memory Diag.app",
  "microsoftexcel": "/Applications/Microsoft Excel.app",
  "microsoftpowerpoint": "/Applications/Microsoft PowerPoint.app",
  "microsoftword": "/Applications/Microsoft Word.app",
  "notionweb": "/Applications/Notion Web Clipper.app",
"ppteditor": "/Applications/PPT-Editor.app",
  "pock": "/Applications/Pock.app",
  "postman": "/Applications/Postman.app",
  "pritunl": "/Applications/Pritunl.app",
  "protonvpn": "/Applications/ProtonVPN.app",
  "pycharm": "/Applications/PyCharm.app",
  "python38": "/Applications/Python 3.8.app",
  "reactnative": "/Applications/React Native Debugger.app",
  "rectangle": "/Applications/Rectangle.app",
  "safari": "/Applications/Safari.app",
  "slack": "/Applications/Slack.app",
  "spotify": "/Applications/Spotify.app",
  "telegram": "/Applications/Telegram.app",
  "utilities": "/Applications/Utilities",
  "vlc": "/Applications/VLC.app",
  "visualstudio": "/Applications/Visual Studio Code.app",
  "wine": "/Applications/Wine.app",
  "winebottler": "/Applications/WineBottler.app",
  "wireshark": "/Applications/Wireshark.app",
  "xcode": "/Applications/Xcode.app",
  "xnviewmp": "/Applications/XnViewMP.app",
  "iterm": "/Applications/iTerm.app",
  "pgadmin4": "/Applications/pgAdmin 4.app",
  "zoom": "zoom.us",
}

apiKey = ""
